name: Update prebuilt blobs

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"

jobs:
  update:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        include:
          - module: "Knox'nt blobs"
            path: "unica/patches/deknox"
          - module: "Low-end Samsung Camera app"
            path: "unica/patches/mass_cam"
          - module: "Non-eSE blobs"
            path: "unica/patches/nfc"
          - module: "Optical FOD blobs"
            path: "unica/patches/product_feature/fingerprint/optical_fod"
          - module: "Side fingerprint sensor blobs"
            path: "unica/patches/product_feature/fingerprint/side_fp"
          - module: "Multi resolution blobs"
            path: "unica/patches/product_feature/resolution"
          - module: "Ultra device blobs"
            path: "unica/patches/ultra"
          - module: "UWB blobs"
            path: "unica/patches/uwb"
          - module: "VNDK 30 apex"
            path: "unica/patches/vndk/30"
          - module: "VNDK 31 apex"
            path: "unica/patches/vndk/31"
          - module: "VNDK 33 apex"
            path: "unica/patches/vndk/33"
          - module: "Samsung China apps"
            path: "unica/mods/china"
          - module: "Eureka blobs"
            path: "unica/mods/eureka"
          - module: "(a23xq) OS proprietary blobs"
            path: "target/a23xq/patches/stock_blobs"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Free disk space
        uses: rokibhasansagar/slimhub_actions@main
        with:
          retain: "compiler_cmake"

      - name: Set up build environment
        run: |
          sudo apt update
          DEBIAN_FRONTEND=noninteractive sudo apt install -yq \
            attr ccache clang ffmpeg golang \
            libbrotli-dev libgtest-dev libprotobuf-dev libunwind-dev libpcre2-dev \
            libzstd-dev linux-modules-extra-$(uname -r) lld protobuf-compiler webp \
            zipalign
          sudo modprobe erofs f2fs
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          echo -n "${{ secrets.PLATFORM_KEY_PK8 }}" | base64 --decode > unica/security/unica_platform.pk8
          echo -n "${{ secrets.PLATFORM_KEY_PEM }}" | base64 --decode > unica/security/unica_platform.x509.pem

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "11"
          cache: "gradle"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"

      - name: Build dependencies
        run: source ./buildenv.sh a23xq

      - name: Update prebuilt blobs
        run: |
          source ./buildenv.sh a23xq
          ./scripts/internal/update_prebuilt_blobs.sh ${{ matrix.path }}
          echo "PDA_BUILD=$(cat ./${{ matrix.path }}/.current | cut -d "/" -f 1)" >> $GITHUB_ENV

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          add-paths: |
            ${{ matrix.path }}
          commit-message: "${{ matrix.path }}: update blobs to ${{ env.PDA_BUILD }}"
          committer: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          branch: "${{ matrix.path }}"
          delete-branch: true
          title: "Update ${{ matrix.path }} blobs to ${{ env.PDA_BUILD }}"
          body: ""
